### ISSUE TITLE
Can I know the version number of your library?

### ISSUE THREAD

**Issue by xingyu-deng** [jpdominguez/Multilayer-SNN-for-audio-samples-classification-using-SpiNNaker#2]
There are many errors caused by unavailable functions with the latest version.  Could you please give me the version number of the libraries? (I think it includes pyNAVIS, pyNN and spinnaker) It will be very helpful.

Thank you very much in advance!

**Comment by dgutierrezATC** [comment]
The file Main_SNN_Trainer.py has been updated with the newest version of pyNAVIS (v1.1.0) to avoid the errors you have mentioned.

The code has been successfully tested and it works.
